// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufzcdplsltxijsnrlueg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmemNkcGxzbHR4aWpzbnJsdWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzMzODcsImV4cCI6MjA3MDUwOTM4N30.e0WaIh1J_9_2FycqEqT-p0xwXWVSu9VUjkgfOMpUfiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
